### ISSUE TITLE
[BoringSSL] nw_protocol_boringssl_get_output_frames(1301) [C3.1:2][0x101f1c190] get output frames failed

### ISSUE THREAD

**Issue by kironet** [loopwxservices/WXKDarkSky#11]
Hi,
I'm new to whole iOS development and sometimes I'm getting this "error?". And when I'm getting this it looks like data are synchronised a little bit slower.

```
2018-10-17 14:35:09.231199+1100 WeatherOutside[424:57727] [BoringSSL] nw_protocol_boringssl_get_output_frames(1301) [C3.1:2][0x101f1c190] get output frames failed, state 8196
2018-10-17 14:35:09.231471+1100 WeatherOutside[424:57727] [BoringSSL] nw_protocol_boringssl_get_output_frames(1301) [C3.1:2][0x101f1c190] get output frames failed, state 8196
2018-10-17 14:35:09.232281+1100 WeatherOutside[424:57727] TIC Read Status [3:0x0]: 1:57
2018-10-17 14:35:09.232341+1100 WeatherOutside[424:57727] TIC Read Status [3:0x0]: 1:57
```

**Comment by jonblatho** [comment]
Sorry for the delayed response! I've run into this logging in various projects, but I haven't run into any actual issues in terms of being able to load data and haven't noticed any different in speed, etc. If you're running into issues loading data from this, though, some [additional logging](https://developer.apple.com/library/content/qa/qa1887/_index.html#//apple_ref/doc/uid/DTS40015177-CH1-SECLOGGINGWITHOUTXCODE) would be extremely helpful in diagnosing the issue.

**Comment by jonblatho** [comment]
This has gone well over a month without a response, so I'm going to close the issue and leave it unlocked for further comment if anyone else runs into this so that I can look more into it.

My understanding, though, is that this is just harmless logging from iOS and can be safely ignored if there aren't any issues with loading data.

**Comment by cjbhojani** [comment]
Hello @jonblatho 
I am also facing this issue.
If you solve this please help me out....!

**Comment by jonblatho** [comment]
@cjbhojani is it causing issues with loading data? My understanding from looking online is that this is harmless logging from iOS.

**Comment by charles-dr** [comment]
Hello, same issue here.
I updated the MacOS and XCode to the latest version and it showing this error.
Hello @jonblatho , what do you mean 'harmless logging from iOS' ?
Do you have any solution ?
Then please help me..

**Comment by jonblatho** [comment]
@TaiJinYuan, it’s not an error and it does not impact functionality. It can be ignored.

**Comment by charles-dr** [comment]
Oh, really, Thank you for your reply.

**Comment by ddesignercoder** [comment]
But My iOS app going crashed automatically..

**Comment by jonblatho** [comment]
Even if this is causing the crashes, and I’m still not inclined to believe that it is, I would like to note that WXKDarkSky is **not** supported for client-side requests, as noted both here and in the inline documentation (the below is borrowed from this project’s README):

> ***IMPORTANT!*** Do **NOT** make requests through WXKDarkSky's networking code if the code is run client-side. Doing so puts your API key at risk of being compromised. It's best to use your own networking code to obtain Dark Sky data from a custom server-side solution that simply re-serves Dark Sky output so that your API key cannot be exposed. (You can even use WXKDarkSky's networking code with server-side Swift frameworks like Vapor or Perfect if your project allows for it.)

There are two big reasons why using WXKDarkSky for client-side requests is risky:

1. Your API key may be compromised should someone manage to decompile your app. Decompilation for iOS apps from the App Store is difficult but certainly not impossible if someone wants to do it that badly. (You could check server-side for a current API key, but that also leaves your API key at risk of being exposed for unauthorized use.)
3. Should your API key otherwise become compromised, you are encouraged to reset your Dark Sky API key. However, your old, compromised key is deactivated, meaning you must both update your app and get your users onto the new version should your API key ever change.

Therefore, I’m not planning on investigating this issue further unless it’s also impacting macOS and/or Linux because it appears to be related to a use case that is unsupported anyway. I’ve strongly considered either removing the functionality on platforms that aren’t macOS or Linux (i.e., server-side Swift) or removing the networking functionality altogether for this reason — using it for client-side requests is absolutely unsupported and will never be supported, full stop.

If you’d like to use WXKDarkSky client-side, obtain a Dark Sky response from **your** server (**not** Dark Sky’s directly) and decode the response through the `DarkSkyResponse(data:)` initializer for use in code. Any other approach is strongly advised against by both us and Dark Sky because of the risks that come with exposing your API key to unauthorized use, including monetary risks.

Sorry for any inconvenience this has caused, but as of now, this is a won’t-fix issue.
